### ISSUE TITLE
Please make this package Laravel 10 compatible/compliant

### ISSUE THREAD

**Issue by mfutselaar** [jigar-dhulla/laravel-http-to-curl#1]
As per version 10 of Laravel, they recommend/require the `minimal-stability` attribute in the composer.json to be `stable`.

```
[Minimum Stability](https://laravel.com/docs/10.x/upgrade#updating-minimum-stability)

You should update the minimum-stability setting in your application's composer.json file to stable
```

This causes the upgrade to fail if you have this package installed.

```
  Problem 1
    - Root composer.json requires jigarakatidus/laravel-http-to-curl ^1.0.0-alpha -> satisfiable by jigarakatidus/laravel-http-to-curl[1.0.0-alpha].
    - jigarakatidus/laravel-http-to-curl 1.0.0-alpha requires jigarakatidus/command-line-generator ^1.0.0-alpha -> found jigarakatidus/command-line-generator[1.0.0-alpha] but it does not match your minimum-stability.
```

I tried reverting the minimum stability back to what it was before but that breaks the upgrade process  entirely.

You don't need to update any code, the version numbering should be fixed.

**Comment by jigar-dhulla** [comment]
Done.

Let me know if you still face any issues.

Thanks for reporting.

**Comment by mfutselaar** [comment]
Thank you! The upgrade ran without any issues now.
